### ISSUE TITLE
1.16.5 world update incompatibility

### ISSUE THREAD

**Issue by Arkadexus** [b3spectacled/modern-beta-fabric#18] opened 2021-01-23 18:58 UTC
Steps to reproduce:
-Create a world in 1.16.4 with Modern Biomes and Beta generation (Haven't tested if it works in other presets)
-Update to 1.16.5 (fabric included)

After this, nether portals stop working completely and some random chunks in the world get replaced or even generate as "indev hell", they keep the same terrain as in beta and all, but the sky colour does get affected

**Comment by b3spectacled** [comment] 2021-01-23 20:16
~~Do you have a mod or data pack with custom dimensions?~~  Either way, my understanding is that it is possibly an issue on Minecraft's end; if you are using custom dimensions or modded chunk generators and update from 1.16.4 to 1.16.5, the Nether and End dimensions are nuked.  You should be able to confirm this by turning on cheats and checking the available dimensions with the 'execute in' command.

There's some discussion on the issue and a workaround for restoring the Nether/End dimensions here: https://bugs.mojang.com/browse/MC-197860

As for the weird biome assignment, you could possibly use a map editor like MCASelector, and delete the biome data for the affected area (see the Updating Old Worlds section of the CF description) so the game can reassign the correct biomes.

Sorry about this.

EDIT: Oop, my bad, can't read.  

EDIT 2: I've tried but can't reproduce. :\ Can you provide error log, if there are any errors, when you attempt to load the world in 1.16.5?

**Comment by Arkadexus** [comment] 2021-01-23 20:29
Found a solution! You have to enter the level.dat with a NBT editor (NBTExplorer is the best) and delete "Dimensions" inside of "WorldGenSettings", which readds the nether and end into the savefile, looks like the upgrade from 1.16.4 to 1.16.5 deletes any generated dimensions due to the bug that you mentioned, so deleting that tag forces minecraft to add them back in again, I kept my chunks in both the end and nether too, so that's nice!

Steps to get the dimensions back before this bug is fixed:

Open level.dat
Go to Data -> WorldGenSettings, and delete the dimensions tag

I'll see if it fixes the indev:hell biomes too

**Comment by Arkadexus** [comment] 2021-01-23 20:37
Alright, to keep beta generation (I've been testing around with a copy of my world) you can make a copy of the world, update to 1.16.5 and then either paste nether and end into dimensions, or delete dimensions as I said before and then reincorporate the old "overworld" tag, which still has the modern beta settings

Edit: No indev:hell spotted either

**Closed as completed** 2021-07-09 18:59 UTC
